import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import ErrorPropagation from "@build0.ai/error-propagation";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const jbmono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Build0",
  description: "Generated by Build0",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${jbmono.variable} antialiased`}>
        <ErrorPropagation>{children}</ErrorPropagation>
      </body>
    </html>
  );
}
